language: generic

sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="."
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script: ./runtests